# Add configuration values here, as shown below.
#
SENDGRID_PASSWORD: app33092802@heroku.com
SENDGRID_USERNAME: pol0p0le
SECRET_KEY_BASE:
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
